### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by SlothfulAlfred** [SlothfulAlfred/Air-Pollution-App-CS#18]
We're currently a little behind our ideal schedule which means we probably won't have time to finish our wish list goals. Here is a list of tasks that we still need to do so that we can stay organized and finish on time. 

### Quality assurance

- [x] Add headers to all files
- [x] Finish code review (see pull requests)
- [x] Validation testing + design walkthrough(see details below)

### Validation testing
_Part of the SQA that we need to do. Basically we're going to write up a bunch of steps for people to go through_
_on our app (i.e. "Click the footer to go to our GitHub", "Navigate to the graph tab", etc.). Then we're going to send_
_out those steps to as many people as possible and see their feedback and if there are any bugs. The design walkthrough_
_is just going to be a google forms that we send to a bunch of people to see whether they like the design of our app_
_and if it is easy to follow!_

- [x] Create spreadsheet for validation testing
- [x] Write up the steps in an efficient way (avoid lots of backtracking)
- [x] Create a google forms with some simple questions for our design walkthrough
- [x] Send both the google forms and the spreadsheet to as many people as possible
- [x] Make changes to the app according to the results that we get

### Code

- [x] Finish the GUI prototype
- [x] Finish the map-related functions
- [x] Add different types of graphs (bar graphs, maybe histograms, etc.)
- [x] Change all file paths to relative (no "C:/Users/programs/...)
- [x] Integration testing (waiting on GUI prototype)

### Wish List
_Since we won't have time to make a website, our wish list will be altered slightly._

- [ ] Add more data, for example, electricity consumption or water wastage
- [ ] Find air pollution data for Mexican states and/or other areas of the world
- [ ] Different types of maps like choropleths

So far we're on a decent pace, let's finalize the GUI prototype sooner rather than later and add the smaller details as we go. Keep in mind that when school starts again you'll have less time to work on the project so don't procrastinate. Be aware that the project is due on February 5, so we only have about one month left; that sounds like a lot of time but it isn't so don't delay.
